#!/usr/bin/env bun
/**
 * Generate src/version.ts from the release tag, git describe, or package.json.
 *
 * Resolution order:
 * 1. RELEASE_REF / RELEASE_TAG (overridable; GITHUB_REF cannot be overridden)
 * 2. GITHUB_REF when it is a tag (refs/tags/v1.2.3)
 * 3. git describe
 * 4. package.json version
 */

import { readFileSync, writeFileSync } from 'fs';
import { execSync } from 'child_process';
import { join } from 'path';
import { resolveEmbeddedVersion } from './resolve-version';

function readPackageVersion(): string | undefined {
  try {
    const packageJson = JSON.parse(
      readFileSync(join(import.meta.dir, '..', 'package.json'), 'utf-8'),
    ) as { version?: string };
    return packageJson.version;
  } catch {
    return undefined;
  }
}

function readGitDescribe(): string | null {
  try {
    return execSync('git describe --tags --always --dirty', {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'ignore'],
    }).trim();
  } catch {
    console.log('⚠ Git not available, falling back to package.json');
    return null;
  }
}

function generateVersionFile() {
  const gitDescribe = readGitDescribe();
  const version = resolveEmbeddedVersion({
    releaseRef: process.env.RELEASE_REF,
    releaseTag: process.env.RELEASE_TAG,
    githubRef: process.env.GITHUB_REF,
    gitDescribe,
    packageVersion: readPackageVersion(),
    // Release runners set CI. bun install dirties the tree on an exact tag,
    // and the binary should still report that tag.
    stripDirty: process.env.CI === 'true' || process.env.CI === '1',
  });

  if (process.env.RELEASE_REF?.startsWith('refs/tags/') || process.env.RELEASE_TAG) {
    console.log(`✓ Using version from release env: ${version}`);
  } else if (process.env.GITHUB_REF?.startsWith('refs/tags/')) {
    console.log(`✓ Using version from GitHub tag: ${version}`);
  } else if (gitDescribe && version !== readPackageVersion()) {
    console.log(`✓ Using version from git describe: ${version}`);
  } else if (version === '0.0.0-unknown') {
    console.error('✗ Failed to read package.json');
  } else {
    console.log(`✓ Using version from package.json: ${version}`);
  }

  const outputPath = join(process.cwd(), 'src', 'version.ts');
  const content = `/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/generate-version.ts
 * Version extracted from Git tag or package.json
 */

export const VERSION = '${version}';
`;

  writeFileSync(outputPath, content, 'utf-8');
  console.log(`✓ Generated ${outputPath}`);
  console.log(`  VERSION = '${version}'`);
}

generateVersionFile();
