#!/usr/bin/env bun
/**
 * Generate src/version.ts from Git tag or package.json
 * 
 * This script extracts the version from:
 * 1. Git tag (if GITHUB_REF is set, e.g., refs/tags/v1.2.3)
 * 2. Git describe (if in a git repository)
 * 3. package.json version (fallback)
 */

import { writeFileSync } from 'fs';
import { execSync } from 'child_process';
import { join } from 'path';

function getVersion(): string {
  // 1. Try GitHub Actions environment variable (GITHUB_REF = refs/tags/v1.2.3)
  const githubRef = process.env.GITHUB_REF;
  if (githubRef && githubRef.startsWith('refs/tags/')) {
    const tag = githubRef.replace('refs/tags/', '');
    const version = tag.startsWith('v') ? tag.slice(1) : tag;
    console.log(`✓ Using version from GitHub tag: ${version}`);
    return version;
  }

  // 2. Try git describe (for local development)
  try {
    const gitDescribe = execSync('git describe --tags --always --dirty', {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'ignore']
    }).trim();
    
    // If it's a clean tag (e.g., v1.2.3), use it
    if (gitDescribe.match(/^v?\d+\.\d+\.\d+$/)) {
      const version = gitDescribe.startsWith('v') ? gitDescribe.slice(1) : gitDescribe;
      console.log(`✓ Using version from git tag: ${version}`);
      return version;
    }
    
    // If it's a describe with commits after tag (e.g., v1.2.3-5-gabcdef), parse it
    const match = gitDescribe.match(/^v?(\d+\.\d+\.\d+)-(\d+)-g([a-f0-9]+)(-dirty)?$/);
    if (match) {
      const [, baseVersion, commits, hash, dirty] = match;
      const version = `${baseVersion}-dev.${commits}+${hash}${dirty || ''}`;
      console.log(`✓ Using version from git describe: ${version}`);
      return version;
    }
  } catch (error) {
    // Git not available or not in a repository
    console.log('⚠ Git not available, falling back to package.json');
  }

  // 3. Fallback to package.json
  try {
    const packageJson = JSON.parse(
      execSync('cat package.json', { encoding: 'utf-8' })
    );
    const version = packageJson.version;
    console.log(`✓ Using version from package.json: ${version}`);
    return version;
  } catch (error) {
    console.error('✗ Failed to read package.json');
    return '0.0.0-unknown';
  }
}

function generateVersionFile() {
  const version = getVersion();
  const outputPath = join(process.cwd(), 'src', 'version.ts');
  
  const content = `/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/generate-version.ts
 * Version extracted from Git tag or package.json
 */

export const VERSION = '${version}';
`;

  writeFileSync(outputPath, content, 'utf-8');
  console.log(`✓ Generated ${outputPath}`);
  console.log(`  VERSION = '${version}'`);
}

// Run the script
generateVersionFile();
